version: '3.8'
services:
  pystan:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./stan:/app
    ports:
      - "8888:8888"
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
